#include <iostream>
using namespace std;

int main()
{
    int element_no;
    string i;
    int atm;
    cout<<"------------------------------------Perodic Table-------------------------------------------"<<endl;
    cout<<"\n                 Welcome To Modern Periodic Table";
cout<<"\n              !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ";
cout<<" \n                                                          ";
cout<<"\n ******************Introduction Of Modern Periodic Table*********************";
cout<<"\n                -------------------------------------   \n   ";

cout<<"\n          Advantages Of this Program   ";
cout<<"\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                        ";
cout<<"\n                        ";

cout<<"\n1.first of all you can easly search the element.";
cout<<"\n                        ";

cout<<"\n2.you can see the periodic table.";
cout<<"\n                        ";

cout<<"\n3.you can easly search the element by their Atomic Number.";
cout<<"\n                        ";
cout<<"\n            Admin of this program						  ";
cout<<"\n          ::::::::::::::::::::::::::                                         ";
cout<<"\n            ";
cout<<"\n          NAME:- Ram Prasann Pandey";
cout<<"\n                 ------------------- ";
cout<<"\n         CLASS:-XI-SCIENCE";
cout<<"\n                <<<<<>>>>>                                                       ";
cout<<"\n                                                                 ";
cout<<"\n                                                               ";
cout<<"\n                                     ";
cout<<"\n                                     ";
cout<<"\n|H|                                                                 |He|";
cout<<"\n|Li||Be|                                        |B ||C ||N ||O ||F ||Ne|";
cout<<"\n|Na||Mg|                                        |Al||Si||P ||S ||Cl||Ar|";
cout<<"\n|K| |Ca||Sc||Ti||V|||Cr||Mn||Fe||Co||Ni||Cu||Zn||Ga||Ge||As||Se||Br||Kr|";
cout<<"\n|Rb||Sr||Y ||Zr||Nb||Mo||Tc||Ru||Rh||Pd||Ag||Cd||In||Sn||Sb||Te|| I||Xe|";
cout<<"\n|Cs||Ba||La||Hf||Ta||W ||Re||Os||Ir||Pt||Au||Hg||Tl||Pb||Bi||Po||At||Rn|";
cout<<"\n|Fr||Ra||lr||Rf||Db||Sg||Bh||Hs||Mt||Ds||Rg||uub||uUt||uuq||Uup||UUh|";
cout<<"\n                           F-inner transition element                  ";
cout<<"\n*lanthanoid|la||Ce||Pr||Nd||Pm||sm||Eu||Gd||Tb||Dy||Ho||Er||Tm||Yb||Lu|";
cout<<"\n**Actinoid |Ac||Th||Pa||U ||Np||pu||Am||Cm||Bk||Cf||Es||Fm||Md||No||Lr|";
cout<<"\n";
cout<<"\n";
cout<<"Information about Perodic Table say [yes or Yes or y or Y] or exit the perodic table say [no]:-";
    cin>>i;
    cout<<endl;
    
    while (i=="yes"||i=="Y"||i=="y"||i=="yes")
    {
        cout<<"\n      Enter the Atomic Number of the Element:-";
        cin>>atm;
cout<<"\n      ****************************************";

switch(atm)
       {
       case 1:cout<<"\nIts-Hydrogen ";
       cout<<"\nAtomic number-1";
       cout<<"\nAtomic weight-1";
       cout<<"\nSymbol-H";
       cout<<"\nDate discovered-1799";
       break;
	 case 2:cout<<"\nIts-Helium";
       cout<<"\nAtomic number-2";
       cout<<"\nAtomic weight-4";
       cout<<"\nSymbol-He";
       cout<<"\nDate discovered-1866";
       break;
       case 3:cout<<"\nIts-Lithium";
       cout<<"\nAtomic number-3";
       cout<<"\nAtomic weight-7";
       cout<<"\nSymbol-Li";
       cout<<"\nDate discovered-1817";
       break;
       case 4:cout<<"\nIts-Beryllium";
       cout<<"\nAtomic number-4";
       cout<<"\nAtomic weight-9";
       cout<<"\nSymbol-Be";
       cout<<"\nDate discovered-1798";
       break;
       case 5:cout<<"\nIts -Boron";
       cout<<"\nAtomic number-5";
       cout<<"\nAtomic weight-10";
       cout<<"\nSymbol-B";
       cout<<"\nDate discovered-1808";
       break;
       case 6:cout<<"\nIts-Carbon";
       cout<<"\nAtomic number-6";
       cout<<"\nAtomic weight-12";
       cout<<"\nSymbol-C";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 7:cout<<"\nIts-Nitrogen";
       cout<<"\nAtomic number-7";
       cout<<"\nAtomic weight-14";
       cout<<"\nSymbol-N";
       cout<<"\nDate discovered-1772";
       break;
       case 8:cout<<"\nIts-Oxygen";
       cout<<"\nAtomic number-8";
       cout<<"\nAtomic weight-16";
       cout<<"\nSymbol-O";
       cout<<"\nDate discovered-  1774";
       break;
       case 9:cout<<"\nIts-Fluorine";
       cout<<"\nAtomic number-9";
       cout<<"\nAtomic weight-19";
       cout<<"\nSymbol-F";
       cout<<"\nDate discovered-1772";
       break;
       case 10:cout<<"\nIts-Neon";
       cout<<"\nAtomic number-10";
       cout<<"\nAtomic weight-20";
       cout<<"\nSymbol-N";
       cout<<"\nDate discovered-1898";
       break;
       case 11:cout<<"\nIts-Sodium";
       cout<<"\nAtomic number-11";
       cout<<"\nAtomic weight-23";
       cout<<"\nSymbol-Na";
       cout<<"\nDate discovered-1807";
       break;
       case 12:cout<<"\nIts-Magnessium";
       cout<<"\nAtomic number-12";
       cout<<"\nAtomic weight-24";
       cout<<"\nSymbol-Mg";
       cout<<"\nDate discovered-1755";
       break;
       case 13:cout<<"\nIts-Aluminium";
       cout<<"\nAtomic number-13";
       cout<<"\nAtomic weight-27";
       cout<<"\nSymbol-Al";
       cout<<"\nDate discovered-1824";
       break;
       case 14:cout<<"\nIts-Silicon";
       cout<<"\nAtomic number-14";
       cout<<"\nAtomic weight-28";
       cout<<"\nSymbol-Si";
       cout<<"\nDate discovered-1832";
       break;
       case 15:cout<<"\nIts-Phosphorus";
       cout<<"\nAtomic number-15";
       cout<<"\nAtomic weight-31";
       cout<<"\nSymbol-P";
       cout<<"\nDate discovered-1674";
       break;
       case 16:cout<<"\nIts-sulphur";
       cout<<"\nAtomic number-16";
       cout<<"\nAtomic weight-32";
       cout<<"\nSymbol-S";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 17:cout<<"\nIts-Chlorine";
       cout<<"\nAtomic number-17";
       cout<<"\nAtomic weight-35";
       cout<<"\nSymbol-Cl";
       cout<<"\nDate discovered-1774";
       break;
       case 18:cout<<"\nIts-Argon";
       cout<<"\nAtomic number-18";
       cout<<"\nAtomic weight-39";
       cout<<"\nSymbol-Ar";
       cout<<"\nDate discovered-1894";
       break;
       case 19:cout<<"\nIts-Potassium";
       cout<<"\nAtomic number-19";
       cout<<"\nAtomic weight-39";
       cout<<"\nSymbol-K";
       cout<<"\nDate discovered-1807";
       break;
       case 20:cout<<"\nIts-Calcium";
       cout<<"\nAtomic number-20";
       cout<<"\nAtomic weight-40";
       cout<<"\nSymbol-Ca";
       cout<<"\nDate discovered-1808";
       break;
       case 21:cout<<"\nIts-scandium";
       cout<<"\nAtomic number-21";
       cout<<"\nAtomic weight-44";
       cout<<"\nSymbol-Sc";
       cout<<"\nDate discovered-1876";
       break;
       case 22:cout<<"\nIts-Titanium";
       cout<<"\nAtomic number-22";
       cout<<"\nAtomic weight-47";
       cout<<"\nSymbol-Ti";
       cout<<"\nDate discovered-1790";
       break;
       case 23:cout<<"\nIts-Vanadium";
       cout<<"\nAtomic number-23";
       cout<<"\nAtomic weight-50";
       cout<<"\nSymbol-V";
       cout<<"\nDate discovered-1801";
       break;
       case 24:cout<<"\nIts-Chromium";
       cout<<"\nAtomic number-24";
       cout<<"\nAtomic weight-52";
       cout<<"\nSymbol-cr";
       cout<<"\nDate discovered-1797";
       break;
       case 25:cout<<"\nIts-Manganese";
       cout<<"\nAtomic number-25";
       cout<<"\nAtomic weight-55";
       cout<<"\nSymbol-Mn";
       cout<<"\nDate discovered-1774";
       break;
       case 26:cout<<"\nIts-Iron";
       cout<<"\nAtomic number- 26";
       cout<<"\nAtomic weight-55";
       cout<<"\nSymbol-Fe";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 27:cout<<"\nIts-cobalt";
       cout<<"\nAtomic number-27";
       cout<<"\nAtomic weight-58";
       cout<<"\nSymbol-Co";
       cout<<"\nDate discovered-1730";
       break;
       case 28:cout<<"\nIts-Nickel";
       cout<<"\nAtomic number-28";
       cout<<"\nAtomic weight-59";
       cout<<"\nSymbol-Ni";
       cout<<"\nDate discovered-1751";
       break;
       case 29:cout<<"\nIts-copper";
       cout<<"\nAtomic number-29";
       cout<<"\nAtomic weight-63";
       cout<<"\nSymbol-Cu";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 30:cout<<"\nIts-Zinc";
       cout<<"\nAtomic number-30";
       cout<<"\nAtomic weight-65";
       cout<<"\nSymbol-Zn";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 31:cout<<"\nIts-Gallium";
       cout<<"\nAtomic number-31";
       cout<<"\nAtomic weight-69";
       cout<<"\nSymbol-Ga";
       cout<<"\nDate discovered-1875";
       break;
       case 32:cout<<"\nItsGermanium";
       cout<<"\nAtomic number-32";
       cout<<"\nAtomic weight-72";
       cout<<"\nSymbol-Ge";
       cout<<"\nDate discovered-1886";
       break;
       case 33:cout<<"\nIts-Arsenic";
       cout<<"\nAtomic number-33";
       cout<<"\nAtomic weight-75";
       cout<<"\nSymbol-As";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 34:cout<<"\nIts-Selenium";
       cout<<"\nAtomic number-34";
       cout<<"\nAtomic weight-78";
       cout<<"\nSymbol-Se";
       cout<<"\nDate discovered-1817";
       break;
       case 35:cout<<"\nIts-Bromine";
       cout<<"\nAtomic number-35";
       cout<<"\nAtomic weight-79";
       cout<<"\nSymbol-Br";
       cout<<"\nDate discovered-1826";
       break;
       case 36:cout<<"\nIts-krypton";
       cout<<"\nAtomic number-36";
       cout<<"\nAtomic weight-83";
       cout<<"\nSymbol-kr";
       cout<<"\nDate discovered-1898";
       break;
       case 37:cout<<"\nIts-Rubidium";
       cout<<"\nAtomic number-37";
       cout<<"\nAtomic weight-85";
       cout<<"\nSymbol-Rb";
       cout<<"\nDate discovered-1861";
       break;
       case 38:cout<<"\nIts-strotium";
       cout<<"\nAtomic number-38";
       cout<<"\nAtomic weight-87";
       cout<<"\nSymbol-Sr";
       cout<<"\nDate discovered-1808";
       break;
       case 39:cout<<"\nIts-Yttrium";
       cout<<"\nAtomic number-39";
       cout<<"\nAtomic weight-89";
       cout<<"\nSymbol-Y";
       cout<<"\nDate discovered-1794";
       break;
       case 40:cout<<"\nIts-Zirconium";
       cout<<"\nAtomic number-40";
       cout<<"\nAtomic weight-91";
       cout<<"\nSymbol-Zr";
       cout<<"\nDate discovered-1789";
       break;
       case 41:cout<<"\nIts-Niobium";
       cout<<"\nAtomic number-41";
       cout<<"\nAtomic weight-92";
       cout<<"\nSymbol-Nb";
       cout<<"\nDate discovered-1891";
       break;
       case 42:cout<<"\nIts-Molybdenum";
       cout<<"\nAtomic number-42";
       cout<<"\nAtomic weight-95";
       cout<<"\nSymbol-Mo";
       cout<<"\nDate discovered-1781";
       break;
       case 43:cout<<"\nIts-Technetium";
       cout<<"\nAtomic number-43";
       cout<<"\nAtomic weight-98";
       cout<<"\nSymbol-Tc";
       cout<<"\nDate discovered-1937";
       break;
       case 44:cout<<"\nIts-Ruthenium";
       cout<<"\nAtomic number-44";
       cout<<"\nAtomic weight-101";
       cout<<"\nSymbol-Ru";
       cout<<"\nDate discovered-1827";
       break;
       case 45:cout<<"\nIts-Rhodium";
       cout<<"\nAtomic number-45";
       cout<<"\nAtomic weight-103";
       cout<<"\nSymbol-Rh";
       cout<<"\nDate discovered-1804";
       break;
       case 46:cout<<"\nIts-palladium";
       cout<<"\nAtomic number- 46";
       cout<<"\nAtomic weight-106";
       cout<<"\nSymbol-Pd";
       cout<<"\nDate discovered-1804";
       break;
       case 47:cout<<"\nIts-Silver";
       cout<<"\nAtomic number-47";
       cout<<"\nAtomic weight-108";
       cout<<"\nSymbol-Ag";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 48:cout<<"\nIts-Cadmium";
       cout<<"\nAtomic number-48";
       cout<<"\nAtomic weight-112";
       cout<<"\nSymbol-Cd";
       cout<<"\nDate discovered-1817";
       break;
       case 49:cout<<"\nIts-indium";
       cout<<"\nAtomic number-49";
       cout<<"\nAtomic weight-115";
       cout<<"\nSymbol-In";
       cout<<"\nDate discovered-1863";
       break;
       case 50:cout<<"\nIts-Tin";
       cout<<"\nAtomic number-50";
       cout<<"\nAtomic weight-119";
       cout<<"\nSymbol-Sn";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 51:cout<<"\nIts Antinomy ";
       cout<<"\nAtomic number-51";
       cout<<"\nAtomic weight-121";
       cout<<"\nSymbol-Sb";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 52:cout<<"\nIts Tellurium";
       cout<<"\nAtomic number-52";
       cout<<"\nAtomic weight-127";
       cout<<"\nSymbol-Te";
       cout<<"\nDate discovered-1782";
       break;
       case 53:cout<<"\nIts Iodine";
       cout<<"\nAtomic number- 53";
       cout<<"\nAtomic weight-128";
       cout<<"\nSymbol-I";
       cout<<"\nDate discovered-1811";
       break;
       case 54:cout<<"\nIts Xenon";
       cout<<"\nAtomic number-54";
       cout<<"\nAtomic weight-131";
       cout<<"\nSymbol-Xe";
       cout<<"\nDate discovered-1898";
       break;
       case 55:cout<<"\nIts Cesium";
       cout<<"\nAtomic number-55";
       cout<<"\nAtomic weight-133";
       cout<<"\nSymbol-Cs";
       cout<<"\nDate discovered-1860";
       break;
       case 56:cout<<"\nIts Barium";
       cout<<"\nAtomic number- 56";
       cout<<"\nAtomic weight-137";
       cout<<"\nSymbol-Ba";
       cout<<"\nDate discovered-1808";
       break;
       case 57:cout<<"\nIts Lanthanum ";
       cout<<"\nAtomic number-57";
       cout<<"\nAtomic weight-140";
       cout<<"\nSymbol-La";
       cout<<"\nDate discovered-1839";
       break;
       case 58:cout<<"\nIts Cerium ";
       cout<<"\nAtomic number-58";
       cout<<"\nAtomic weight-140";
       cout<<"\nSymbol-Ce";
       cout<<"\nDate discovered-1804";
       break;
       case 59:cout<<"\nIts Praseodymium ";
       cout<<"\nAtomic number-59";
       cout<<"\nAtomic weight-141";
       cout<<"\nSymbol-Pr";
       cout<<"\nDate discovered-1885";
       break;
       case 60:cout<<"\nIts Neodymium";
       cout<<"\nAtomic number-60";
       cout<<"\nAtomic weight-144";
       cout<<"\nSymbol-Nd";
       cout<<"\nDate discovered-1885";
       break;
       case 61:cout<<"\nIts Promethium ";
       cout<<"\nAtomic number-61";
       cout<<"\nAtomic weight-145";
       cout<<"\nSymbol-Pm";
       cout<<"\nDate discovered-1945";
       break;
       case 62:cout<<"\nIts Samarium";
       cout<<"\nAtomic number-62";
       cout<<"\nAtomic weight-150";
       cout<<"\nSymbol-Sm";
       cout<<"\nDate discovered-1879";
       break;
       case 63:cout<<"\nIts Europium";
       cout<<"\nAtomic number-63";
       cout<<"\nAtomic weight-152";
       cout<<"\nSymbol-Eu";
       cout<<"\nDate discovered-1901";
       break;
       case 64:cout<<"\nIts Gadolinium";
       cout<<"\nAtomic number-64";
       cout<<"\nAtomic weight-157";
       cout<<"\nSymbol-Gd";
       cout<<"\nDate discovered-1886";
       break;
       case 65:cout<<"\nIts Terbium";
       cout<<"\nAtomic number-65";
       cout<<"\nAtomic weight-159";
       cout<<"\nSymbol-Tb";
       cout<<"\nDate discovered-1843";
       break;
       case 66:cout<<"\nIts Dysprosium";
       cout<<"\nAtomic number-66";
       cout<<"\nAtomic weight-162";
       cout<<"\nSymbol-Dy";
       cout<<"\nDate discovered-1886";
       break;
       case 67:cout<<"\nIts Holmium";
       cout<<"\nAtomic number-67";
       cout<<"\nAtomic weight-165";
       cout<<"\nSymbol-Ho";
       cout<<"\nDate discovered-1879";
       break;
       case 68:cout<<"\nIts Erbium";
       cout<<"\nAtomic number-68";
       cout<<"\nAtomic weight-167";
       cout<<"\nSymbol-Er";
       cout<<"\nDate discovered-1843";
       break;
       case 69:cout<<"\nIts Thulium";
       cout<<"\nAtomic number-69";
       cout<<"\nAtomic weight-169";
       cout<<"\nSymbol-Tm";
       cout<<"\nDate discovered-1879";
       break;
       case 70:cout<<"\nIts Ytterbium";
       cout<<"\nAtomic number-70";
       cout<<"\nAtomic weight-173";
       cout<<"\nSymbol-Yb";
       cout<<"\nDate discovered- 1878";
       break;
       case 71:cout<<"\nIts Lutetium ";
       cout<<"\nAtomic number-71";
       cout<<"\nAtomic weight-175";
       cout<<"\nSymbol-Lu";
       cout<<"\nDate discovered- 1907" ;
       break;
       case 72:cout<<"\nIts Hafnium  ";
       cout<<"\nAtomic number- 72";
       cout<<"\nAtomic weight-178";
       cout<<"\nSymbol- Hf";
       cout<<"\nDate discovered-1913";
       break;
       case 73:cout<<"\nIts Tantalum";
       cout<<"\nAtomic number-73";
       cout<<"\nAtomic weight-180";
       cout<<"\nSymbol-Ta";
       cout<<"\nDate discovered-1802";
       break;
       case 74:cout<<"\nIts Tungsten";
       cout<<"\nAtomic number-74";
       cout<<"\nAtomic weight-183";
       cout<<"\nSymbol-W";
       cout<<"\nDate discovered-1783";
       break;
       case 75:cout<<"\nIts Rhenium";
       cout<<"\nAtomic number-75";
       cout<<"\nAtomic weight- 186";
       cout<<"\nSymbol-Re";
       cout<<"\nDate discovered-1925";
       break;
       case 76:cout<<"\nIts Osmium";
       cout<<"\nAtomic number-76";
       cout<<"\nAtomic weight- 190";
       cout<<"\nSymbol-Os";
       cout<<"\nDate discovered-1804";
       break;
       case 77:cout<<"\nIts Iridium";
       cout<<"\nAtomic number-77";
       cout<<"\nAtomic weight-192";
       cout<<"\nSymbol-Ir";
       cout<<"\nDate discovered-1804";
       break;
       case 78:cout<<"\nIts Platinum";
       cout<<"\nAtomic number- 78";
       cout<<"\nAtomic weight-195";
       cout<<"\nSymbol-Pt";
       cout<<"\nDate discovered-1557";
       break;
       case 79:cout<<"\nIts Gold";
       cout<<"\nAtomic number-79";
       cout<<"\nAtomic weight-197";
       cout<<"\nSymbol-Au";
       cout<<"\nDate discovered-Prehistoric";
       break;
       case 80:cout<<"\nIts Mercury ";
       cout<<"\nAtomic number-80";
       cout<<"\nAtomic weight-200";
       cout<<"\nSymbol-Hg";
       cout<<"\nDate discovered-prehistoric";
       break;
       case 81:cout<<"\nIts Thallium";
       cout<<"\nAtomic number-81";
       cout<<"\nAtomic weight-204";
       cout<<"\nSymbol-Tl";
       cout<<"\nDate discovered-1861";
       break;
       case 82:cout<<"\nIts Lead";
       cout<<"\nAtomic number-82";
       cout<<"\nAtomic weight-207";
       cout<<"\nSymbol- pb";
       cout<<"\nDate discovered-prehistoric";
       break;
       case 83:cout<<"\nItsBismuth ";
       cout<<"\nAtomic number-83";
       cout<<"\nAtomic weight-208";
       cout<<"\nSymbol- Bi";
       cout<<"\nDate discovered-prehistoric";
       break;
       case 84:cout<<"\nIts Polonium";
       cout<<"\nAtomic number-84";
       cout<<"\nAtomic weight-209";
       cout<<"\nSymbol-Po";
       cout<<"\nDate discovered-1898";
       break;
       case 85:cout<<"\nItsAstatine ";
       cout<<"\nAtomic number-85";
       cout<<"\nAtomic weight-210";
       cout<<"\nSymbol-At";
       cout<<"\nDate discovered-1940";
       break;
       case 86:cout<<"\nIts Radon";
       cout<<"\nAtomic number-86";
       cout<<"\nAtomic weight-222";
       cout<<"\nSymbol-Rn";
       cout<<"\nDate discovered-1900";
       break;
       case 87:cout<<"\nIts Francium ";
       cout<<"\nAtomic number- 87";
       cout<<"\nAtomic weight-223";
       cout<<"\nSymbol-Fr";
       cout<<"\nDate discovered-1939";
       break;
       case 88:cout<<"\nIts Radium";
       cout<<"\nAtomic number-88";
       cout<<"\nAtomic weight-226";
       cout<<"\nSymbol-Ra";
       cout<<"\nDate discovered-1898";
       break;
       case 89:cout<<"\nIts Actinium";
       cout<<"\nAtomic number-89";
       cout<<"\nAtomic weight-227";
       cout<<"\nSymbol-Ac";
       cout<<"\nDate discovered- 1899";
       break;
       case 90:cout<<"\nIts Thorium";
       cout<<"\nAtomic number-90";
       cout<<"\nAtomic weight-232";
       cout<<"\nSymbol-Th";
       cout<<"\nDate discovered-1828";
       break;
       case 91:cout<<"\nIts Protactinium";
       cout<<"\nAtomic number-91";
       cout<<"\nAtomic weight-231";
       cout<<"\nSymbol-Pa";
       cout<<"\nDate discovered-1913";
       break;
       case 92:cout<<"\nIts Uranium";
       cout<<"\nAtomic number-92";
       cout<<"\nAtomic weight-238";
       cout<<"\nSymbol-U";
       cout<<"\nDate discovered-1789";
       break;
       case 93:cout<<"\nIts Neptunium";
       cout<<"\nAtomic number-93";
       cout<<"\nAtomic weight-237";
       cout<<"\nSymbol-Np";
       cout<<"\nDate discovered-1940";
       break;
       case 94:cout<<"\nIts Plutonium";
       cout<<"\nAtomic number- 94";
       cout<<"\nAtomic weight-244";
       cout<<"\nSymbol-Pu";
       cout<<"\nDate discovered-1940";
       break;
       case 95:cout<<"\nIts Americium";
       cout<<"\nAtomic number-95";
       cout<<"\nAtomic weight- 243";
       cout<<"\nSymbol-Am";
       cout<<"\nDate discovered-1944";
       break;
       case 96:cout<<"\nIts Curium";
       cout<<"\nAtomic number-96";
       cout<<"\nAtomic weight-247";
       cout<<"\nSymbol-Cm";
       cout<<"\nDate discovered-1944";
       break;
       case 97:cout<<"\nIts Berkelium";
       cout<<"\nAtomic number-97";
       cout<<"\nAtomic weight-247";
       cout<<"\nSymbol-Bk";
       cout<<"\nDate discovered-1949";
       break;
       case 98:cout<<"\nIts Californium";
       cout<<"\nAtomic number-98";
       cout<<"\nAtomic weight-251";
       cout<<"\nSymbol-Cf";
       cout<<"\nDate discovered- 1950";
       break;
       case 99:cout<<"\nIts Einsteinium";
       cout<<"\nAtomic number- 99";
       cout<<"\nAtomic weight-252";
       cout<<"\nSymbol-Es";
       cout<<"\nDate discovered-1952";
       break;
       case 100:cout<<"\nIts Fermium";
       cout<<"\nAtomic number-100";
       cout<<"\nAtomic weight-257";
       cout<<"\nSymbol-Fm";
       cout<<"\nDate discovered-1955";
       break;
       case 101:cout<<"\nIts Mendelevium";
       cout<<"\nAtomic number-101";
       cout<<"\nAtomic weight-258";
       cout<<"\nSymbol-Md";
       cout<<"\nDate discovered-1955";
       break;
       case 102:cout<<"\nIts Nobelium";
       cout<<"\nAtomic number-102";
       cout<<"\nAtomic weight-259";
       cout<<"\nSymbol-No";
       cout<<"\nDate discovered-1958";
       break;
       case 103:cout<<"\nIts Lawrncium ";
       cout<<"\nAtomic number-103";
       cout<<"\nAtomic weight-260";
       cout<<"\nSymbol-Lr";
       cout<<"\nDate discovered-1961";
       break;
       case 104:cout<<"\nIts Rutherfordium";
       cout<<"\nAtomic number-104";
       cout<<"\nAtomic weight-261";
       cout<<"\nSymbol-Rf";
       cout<<"\nDate discovered-1969";
       break;
       case 105:cout<<"\nIts Dubnium";
       cout<<"\nAtomic number-105";
       cout<<"\nAtomic weight-262";
       cout<<"\nSymbol-Db";
       cout<<"\nDate discovered-1970";
       break;
       case 106:cout<<"\nIts Seaborgium";
       cout<<"\nAtomic number-106";
       cout<<"\nAtomic weight-266";
       cout<<"\nSymbol-Sg";
       cout<<"\nDate discovered-1974";
       break;
       case 107:cout<<"\nIts Bohrium";
       cout<<"\nAtomic number-107";
       cout<<"\nAtomic weight-262";
       cout<<"\nSymbol-Bh";
       cout<<"\nDate discovered-1976";
       break;
       case 108:cout<<"\nIts Hassium";
       cout<<"\nAtomic number-108";
       cout<<"\nAtomic weight- 263";
       cout<<"\nSymbol-Hs";
       cout<<"\nDate discovered-1984";
       break;
       case 109:cout<<"\nIts Meitnerium";
       cout<<"\nAtomic number-109";
       cout<<"\nAtomic weight-268";
       cout<<"\nSymbol-Mt";
       cout<<"\nDate discovered-1982";
       break;
       case 110:cout<<"\nIts Darmstadtium";
       cout<<"\nAtomic number-110";
       cout<<"\nAtomic weight-271";
       cout<<"\nSymbol- Ds";
       cout<<"\nDate discovered-1994";
       break;
       case 111:cout<<"\nIts Roentgenium";
       cout<<"\nAtomic number-111";
       cout<<"\nAtomic weight-272";
       cout<<"\nSymbol-Rg";
       cout<<"\nDate discovered-1994";
       break;
       case 112:cout<<"\nIts Ununbium";
       cout<<"\nAtomic number-112";
       cout<<"\nAtomic weight-277";
       cout<<"\nSymbol-Uub";
       cout<<"\nDate discovered-1996";
       break;
       case 113:cout<<"\nIts Ununtrium";
       cout<<"\nAtomic number-113";
       cout<<"\nAtomic weight-284";
       cout<<"\nSymbol-Uut";
       cout<<"\nDate discovered-2003";
       break;
       case 114:cout<<"\nIts Ununquadium";
       cout<<"\nAtomic number-114";
       cout<<"\nAtomic weight-285";
       cout<<"\nSymbol-uuq";
       cout<<"\nDate discovered-1998";
       break;
       case 115:cout<<"\nIts Ununpentium";
       cout<<"\nAtomic number-115";
       cout<<"\nAtomic weight-288";
       cout<<"\nSymbol-Uup";
       cout<<"\nDate discovered-2003";
       break;
       case 116:cout<<"\nIts Ununhexium";
		cout<<"\nAtomic number-116";
		cout<<"\nAtomic weight-292";
		cout<<"\nSymbol-Uuh";
		cout<<"\nDate discovered-2000";
		break;
       default:cout<<"\nwrong!choice please enter the atomic number between 1-116 not:-"<<atm;
       }
       cout<<"\n                        ";
       cout<<"\n                        ";
         cout<<endl;
     cout<<"again search the Perodic Table say [yes or Yes or y or Y] or exit the perodic table say [no]"<<endl;
     cin>>i;
     cout<<endl;

       
       }
        cout<<"Exit the Game";
    
    return 0;
}
      

